# -*- coding: utf-8 -*-
"""Fake_News_Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iXTftXnRELdbCSE1fzeaabeQi9VXcHEp

# Fake News Detection
## Ashutosh Gautam
"""

#Mount Google drive
from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
#Change the directory to the path where you have all your input files
# %cd /content/drive/My Drive/Fake-News-Detection
#Below command shows you all thee files present in your current directory
#!ls

#Importing libraries
import numpy as np
import pandas as pd
import itertools

#importing dataset
dataset=pd.read_csv("news.csv")

dataset.shape
dataset.head(10)

#checking labels
labels=dataset.label
labels.head(10)

#training dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(dataset['text'], labels, test_size=0.2, random_state=7)

from sklearn.feature_extraction.text import TfidfVectorizer 
tfidf_vectorizer=TfidfVectorizer(stop_words='english',max_df=0.7)
tfidf_train=tfidf_vectorizer.fit_transform(x_train)
tfidf_test=tfidf_vectorizer.transform(x_test)

#DataFlair - Initialize a PassiveAggressiveClassifier
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
pac=PassiveAggressiveClassifier(max_iter=50)
pac.fit(tfidf_train,y_train)

#DataFlair - Predict on the test set and calculate accuracy
y_pred=pac.predict(tfidf_test)
score=accuracy_score(y_test,y_pred)
print(f'Accuracy: {round(score*100,2)}%')

confusion_matrix(y_test,y_pred, labels=['FAKE','REAL'])